Removes Dockerfile
Even though base image was python:2.7, openshift rewrites this to use centos/python-27-centos7

The pip install -r requirements.txt fails with

```
Traceback (most recent call last):
  File "/opt/app-root/bin/pip", line 7, in <module>
    from pip import main
  File "/opt/app-root/lib/python2.7/site-packages/pip/__init__.py", line 13, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/opt/app-root/lib/python2.7/site-packages/pip/utils/__init__.py", line 15, in <module>
    import zipfile
  File "/opt/rh/python27/root/usr/lib64/python2.7/zipfile.py", line 6, in <module>
    import io
  File "/opt/rh/python27/root/usr/lib64/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /opt/app-root/lib64/python2.7/lib-dynload/_io.so: undefined symbol: _PyErr_ReplaceException
```

Online troubleshooting suggests sourcing an scl_enable command, and that S2I is better for this anyways.

Since I'm simplifying, going to just delete the dockerfile and see if S2I can build/deploy this in one go.