Adds .s2i/bin/assemble script to upgrade pip/setuptools
Per https://stackoverflow.com/questions/46927162/python-2-7-on-openshift-v3-update-setuptools-before-build, and addressing the following error regarding setuptools

```
Requirement already satisfied (use --upgrade to upgrade): setuptools in /opt/app-root/lib/python3.5/site-packages (from cwltool==1.0.20170525215327->-r requirements.txt (line 1))
Collecting ruamel.yaml>=0.12.4 (from cwltool==1.0.20170525215327->-r requirements.txt (line 1))
Downloading ruamel.yaml-0.15.35.tar.gz (260kB)
Complete output from command python setup.py egg_info:
sys.argv ['-c', 'egg_info', '--egg-base', 'pip-egg-info']
Traceback (most recent call last):
File "<string>", line 20, in <module>
File "/tmp/pip-build-ug2uznus/ruamel.yaml/setup.py", line 917, in <module>
main()
File "/tmp/pip-build-ug2uznus/ruamel.yaml/setup.py", line 905, in main
setup(**kw)
File "/opt/rh/rh-python35/root/usr/lib64/python3.5/distutils/core.py", line 108, in setup
_setup_distribution = dist = klass(attrs)
File "/opt/app-root/lib/python3.5/site-packages/setuptools/dist.py", line 272, in __init__
_Distribution.__init__(self,attrs)
File "/opt/rh/rh-python35/root/usr/lib64/python3.5/distutils/dist.py", line 281, in __init__
self.finalize_options()
File "/opt/app-root/lib/python3.5/site-packages/setuptools/dist.py", line 327, in finalize_options
ep.load()(self, ep.name, value)
File "/opt/app-root/lib/python3.5/site-packages/setuptools/dist.py", line 105, in check_extras
if pkg_resources.invalid_marker(m):
File "/opt/app-root/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1416, in is_invalid_marker
cls.evaluate_marker(text)
File "/opt/app-root/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1532, in _markerlib_evaluate
for key in env.keys():
RuntimeError: dictionary changed size during iteration
```